[package]
name = "nop"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "The NOP example: does not do anything."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

