[package]
name = "number-stream-generator"
version = "0.1.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "A utility for generating synthetic 3 data files: *-init.dat containing a single 64-bit floating point number, and *-1.dat and *-2.dat which are two Vecs of 64-bit floating point numbers respectively."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinecone = "0.2"
csv  = "1.0"
serde = { version = "1.0.103", features = ["derive"] }
rand = "0.7"
rand_distr = "0.3"
clap = "2.33"
bitflags = "=1.2.1"
