[package]
name = "veracruz-utils"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Miscellaneous and common code used by multiple Veracruz components.  (A utility library.)"

[features]

sgx = ["sgx_tstd", "serde/mesalock_sgx", "serde_json/mesalock_sgx", "serde_json/alloc", "wasi-types/sgx"]
tz = ["serde_json/std", "wasi-types/std"]
std = ["x509-parser", "serde/std", "rustls","serde_json/std", "actix-web", "futures", "actix-http", "failure", "wasi-types/std"]
nitro = ["serde_json/std", "nix", "byteorder", "wasi-types/std"]

[dependencies]
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
serde = { git = "https://github.com/veracruz-project/serde.git", features=["derive"], branch = "veracruz", rev = "19d2797fe979e15876ad180865ffac5c47d7de9c" }
x509-parser = { version = "0.7.0", optional = true }
serde_json = { git = "https://github.com/veracruz-project/json.git", branch = "veracruz", default-features = false, rev = "30743088aad1afbb8955f88d526d0eb3c4868a14" }
# The cargo patch mechanism does NOT work when we add function into a macro_rules!
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz", optional = true, rev = "39f39964f61b73d333a5f33c3c51d5022ed0af6b" }
actix-web = { version = "3.3.2", optional = true }
futures = { version = "0.3", optional = true }
actix-http = { version = "2.2.0", optional = true }
failure = { version = "0.1", optional = true }
err-derive = "0.2"
nix = { version = "0.15", optional = true }
byteorder = { version = "1.3", optional = true }
hex = { version = "=0.4.2", default-features = false }
wasi-types = { git = "https://github.com/veracruz-project/wasi-types.git", branch = "veracruz", rev = "6120197d776d217e7de7f33fa3185fb62901c13c" }

[build-dependencies]
uuid = { version = "0.7", features = ["v4"] }

[patch.crates-io]
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "self_signed", optional = true, rev = "ae046278ad55ec1d27642051422dd591d0121b5f" }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { branch="veracruz", git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', optional = true, rev = "5a7ad8cae45be8268987ca0d07c25f645593a8c3" }
