[package]
name = "runtime-manager-bind"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Automatically-generated C bindings for the Runtime Manager enclave image."

[dependencies]

[build-dependencies]
bindgen = "0.53.1"
bitflags = "=1.2.1"
