[package]
name = "private-set-intersection-generator"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "A utility for geneting synthetic datasets for use with the `private-set-intersection` example."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinecone = "0.2"
csv = "1.0"
serde = { version = "1.0.103", features = ["derive"] }
clap = "2.33"
bitflags = "=1.2.1"
