[package]
name = "linear-regression"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Another pure-Rust implementation of logistic regression."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinecone = "0.2.3"
serde = { version = "1.0.3", default-features = false, features = ["derive"] }
wasi-types = { git = "https://github.com/veracruz-project/wasi-types.git", branch = "veracruz" }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

