[package]
name = "logistic-regression"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Logistic regression example, using the Rust rusty-machine ML library."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinecone = "0.2.3"
rusty-machine = "0.5.4"
serde = { version = "1.0.3", features = ["derive"] }
wasi-types = { git = "https://github.com/veracruz-project/wasi-types.git", branch = "veracruz" }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

