# AUTHORS
#
# The Veracruz Development Team.
#
# COPYRIGHT
#
# See the `LICENSE_MIT.markdown` file in the Veracruz root directory for licensing
# and copyright information.

[package]
name = "icecap-wrapper"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"

[dependencies]
icecap-core = { path = "../../../icecap/src/rust/crates/icecap/icecap-core" }
icecap-start-generic = { path = "../../../icecap/src/rust/crates/icecap/icecap-start/generic" }
icecap-std-external = { path = "../../../icecap/src/rust/crates/std-support/icecap-std-external" }
icecap-event-server-types = { path = "../../../icecap/src/rust/crates/components/event-server/types" }
