[package]
name = "linear-regression-generator"
version = "0.3.0"
authors = ["Shale Xiong <shale.xiong@arm.com>"]
edition = "2018"
description = "A utility for generating synthetic datasets for use with the `linear-regression` example."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinecone = "0.2"
csv  = "1.0"
serde = { version = "1.0.103", features = ["derive"] }
rand = "0.7"
rand_distr = "0.3"
clap = "2.33"
bitflags = "=1.2.1"
