[package]
name = "idash2017-logistic-regression"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "A Rust reimplementation of the winning logistic regression entry in the IDASH 2017 competition."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinecone = "0.2.3"
wasi-types = { git = "https://github.com/veracruz-project/wasi-types.git", branch = "veracruz" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

