[package]
name = "psa-attestation"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
build = "build.rs"
links="psa_attestation"
description = "An implementation of Arm's PSA attestation protocol."

[lib]
crate-type = ["rlib"]

[features]
# build.rs depends on features
tz = []
sgx = []
nitro = []

[dependencies]
# TODO_BEFORE_MERGE
libc = { git = "https://gitlab.com/arm-research/security/icecap/minor-patches/rust/libc.git", branch = "icecap" }

[build-dependencies]
bindgen = "0.53.1"
cmake = "0.1"
target_build_utils = "0.1"
cfg-if = "1.0"
