name: Veracruz-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # check-repo-and-compile-sdk:
  #   runs-on: ubuntu-latest
  #   container: 
  #     image: ghcr.io/veracruz-project/veracruz/veracruz:ci
  #     volumes: 
  #       - ${{ github.workspace }}:/work/veracruz 

  #   steps:

  #     # Check out the repo, using the action from github
  #     - name: Check out the repo
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: recursive
      
  #     # Compile all examples and data sources in the sdk
  #     - name: Compile SDK
  #       id: sdk
  #       run: |
  #         cd /work/veracruz
  #         make sdk

  #     # Pack cache
  #     - name: Pack cache
  #       id: pack-cache
  #       run: |
  #         cd /
  #         tar -cvf veracruz.tar -C /work/veracruz --exclude=./veracruz.tar --exclude-vcs --exclude-backups .

  #    # Update the repo and sdk artifact, using the action from github
  #     - name: Upload veracruz cache artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: veracruz.tar
  #         path: /veracruz.tar 
  #         if-no-files-found: error

  # sgx:
  #   runs-on: ubuntu-latest
  #   container: 
  #     image: ghcr.io/veracruz-project/veracruz/veracruz:ci
  #     volumes: 
  #       - ${{ github.workspace }}:/work/veracruz 
  #   needs: [check-repo-and-compile-sdk]

  #   steps:
        
  #     # Download the artifact containing repo and sdk artifact, using the action from github
  #     - name: Download veracruz cache artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: veracruz.tar
  #         path: /
  #     # Unpack
  #     - name: Unpack veracruz cache artifact
  #       id: sgx-unpack
  #       run: |
  #           cd /
  #           mkdir -p /work/veracruz
  #           tar -C /work/veracruz -xvf veracruz.tar
  #           rm veracruz.tar
      
  #     # Run the sgx test
  #     - name: Running sgx test script
  #       id: sgx-test
  #       run: |
  #           cd /work/veracruz
  #           make sgx
  #           make sgx-veracruz-server-test-dry-run
  #           make sgx-veracruz-test-dry-run
  #           make sgx-veracruz-client-test
  # tz:
  #   runs-on: ubuntu-latest
  #   container: 
  #     image: ghcr.io/veracruz-project/veracruz/veracruz:ci
  #     volumes: 
  #       - ${{ github.workspace }}:/work/veracruz 
  #   needs: [check-repo-and-compile-sdk]

  #   steps:
        
  #     # Download the artifact containing repo and sdk artifact, using the action from github
  #     - name: Download veracruz cache artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: veracruz.tar
  #         path: /
  #     # Unpack
  #     - name: Unpack veracruz cache artifact
  #       id: tz-unpack
  #       run: |
  #           cd /
  #           mkdir -p /work/veracruz
  #           tar -C /work/veracruz -xvf veracruz.tar
  #           rm veracruz.tar
      
  #     - name: Running trustzone test script
  #       id: tz-test
  #       run: |
  #           cd /work/rust-optee-trustzone-sdk
  #           . ./environment
  #           cd /work/veracruz
  #           make trustzone
  #           make trustzone-veracruz-server-test
  #           make trustzone-veracruz-test
  #           make trustzone-veracruz-client-test

  icecap:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/veracruz-project/veracruz/veracruz-icecap:ci-d581f77edf
      volumes: 
        - ${{ github.workspace }}:/work/veracruz 
    steps:
      - name: Check out the Veracruz repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build and test Veracruz on IceCap
        run: bash /work/veracruz/icecap/ci/run.sh
